import type { Opportunity } from "@/lib/types";

// Generated by lib/generate-corpus.ts (seed 30). Do not hand-edit — rerun
// the generator and re-paste if the corpus needs to change.
export const opportunities: Opportunity[] = [
  {
    id: "opp-01",
    name: "Franchise Program",
    account: "Sparrowhawk Health",
    amount: 49500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-28" }
    ],
    activities: [
      { type: "note", date: "2026-08-28" },
      { type: "note", date: "2026-08-22" }
    ],
  },
  {
    id: "opp-02",
    name: "Global Rollout Phase 2",
    account: "Solstice Retail",
    amount: 141500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-19" },
      { stage: "qualification", enteredDate: "2026-08-26" }
    ],
    activities: [
      { type: "email", date: "2026-08-26" },
      { type: "call", date: "2026-08-20" }
    ],
  },
  {
    id: "opp-03",
    name: "District-Wide License",
    account: "Amberwell Insurance",
    amount: 93500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-13" },
      { stage: "qualification", enteredDate: "2026-08-20" },
      { stage: "demo", enteredDate: "2026-08-27" }
    ],
    activities: [
      { type: "call", date: "2026-08-27" },
      { type: "email", date: "2026-08-21" },
      { type: "note", date: "2026-08-15" }
    ],
  },
  {
    id: "opp-04",
    name: "Multi-Site Rollout",
    account: "Wickerdown Supply",
    amount: 115500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-31" },
      { stage: "qualification", enteredDate: "2026-08-07" },
      { stage: "demo", enteredDate: "2026-08-14" },
      { stage: "proposal", enteredDate: "2026-08-21" }
    ],
    activities: [
      { type: "email", date: "2026-08-21" },
      { type: "note", date: "2026-08-15" },
      { type: "email", date: "2026-08-09" }
    ],
  },
  {
    id: "opp-05",
    name: "Fleet Tracking Add-On",
    account: "Ashgrove Higher Ed",
    amount: 230500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-21" },
      { stage: "qualification", enteredDate: "2026-07-28" },
      { stage: "demo", enteredDate: "2026-08-04" },
      { stage: "proposal", enteredDate: "2026-08-11" }
    ],
    activities: [
      { type: "note", date: "2026-08-11" },
      { type: "email", date: "2026-08-05" }
    ],
  },
  {
    id: "opp-06",
    name: "Add-On Module: Analytics",
    account: "Ledgerline Finance",
    amount: 25500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-29" },
      { stage: "qualification", enteredDate: "2026-08-05" },
      { stage: "demo", enteredDate: "2026-08-12" },
      { stage: "proposal", enteredDate: "2026-08-19" },
      { stage: "negotiation", enteredDate: "2026-08-26" }
    ],
    activities: [
      { type: "note", date: "2026-08-26" },
      { type: "meeting", date: "2026-08-20" },
      { type: "note", date: "2026-08-14" }
    ],
  },
  {
    id: "opp-07",
    name: "Renewal at Risk",
    account: "Aldergate Capital",
    amount: 212000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-19" },
      { stage: "qualification", enteredDate: "2026-07-26" },
      { stage: "demo", enteredDate: "2026-08-02" },
      { stage: "proposal", enteredDate: "2026-08-09" },
      { stage: "negotiation", enteredDate: "2026-08-16" }
    ],
    activities: [
      { type: "note", date: "2026-08-16" },
      { type: "meeting", date: "2026-08-10" }
    ],
  },
  {
    id: "opp-08",
    name: "District-Wide License",
    account: "Granite Manufacturing",
    amount: 137500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-19" },
      { stage: "qualification", enteredDate: "2026-07-26" },
      { stage: "demo", enteredDate: "2026-08-02" },
      { stage: "proposal", enteredDate: "2026-08-09" },
      { stage: "negotiation", enteredDate: "2026-08-16" },
      { stage: "closed-won", enteredDate: "2026-08-23" }
    ],
    activities: [
      { type: "pricing-discussed", date: "2026-08-11" },
      { type: "contract-sent", date: "2026-08-19" },
      { type: "signature-received", date: "2026-08-23" }
    ],
  },
  {
    id: "opp-09",
    name: "Trial Extension Deal",
    account: "Palisade Insurance",
    amount: 304500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-06-27" },
      { stage: "qualification", enteredDate: "2026-07-04" },
      { stage: "demo", enteredDate: "2026-07-11" },
      { stage: "proposal", enteredDate: "2026-07-18" },
      { stage: "negotiation", enteredDate: "2026-07-25" },
      { stage: "closed-won", enteredDate: "2026-08-01" }
    ],
    activities: [
      { type: "contract-sent", date: "2026-07-27" },
      { type: "signature-received", date: "2026-08-01" }
    ],
  },
  {
    id: "opp-10",
    name: "Trial Extension Deal",
    account: "Brackenfield Energy",
    amount: 65000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-25" },
      { stage: "closed-lost", enteredDate: "2026-08-29" }
    ],
    activities: [
      { type: "email", date: "2026-08-25" }
    ],
  },
  {
    id: "opp-11",
    name: "Alumni Portal Upgrade",
    account: "Thistlewood Foods",
    amount: 197000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-22" },
      { stage: "qualification", enteredDate: "2026-08-06" },
      { stage: "closed-lost", enteredDate: "2026-08-13" }
    ],
    activities: [
      { type: "meeting", date: "2026-07-22" },
      { type: "call", date: "2026-07-16" }
    ],
  },
  {
    id: "opp-12",
    name: "Post-Merger Consolidation",
    account: "Copperfield Logistics",
    amount: 54500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-22" },
      { stage: "qualification", enteredDate: "2026-08-29" }
    ],
    activities: [
      { type: "email", date: "2026-08-29" }
    ],
  },
  {
    id: "opp-13",
    name: "Add-On Module: Analytics",
    account: "Quillfeather Media",
    amount: 224500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-06-12" },
      { stage: "qualification", enteredDate: "2026-06-19" },
      { stage: "demo", enteredDate: "2026-06-26" },
      { stage: "proposal", enteredDate: "2026-07-03" },
      { stage: "negotiation", enteredDate: "2026-07-10" }
    ],
    activities: [
      { type: "note", date: "2026-07-10" },
      { type: "call", date: "2026-07-04" }
    ],
  },
  {
    id: "opp-14",
    name: "Renewal at Risk",
    account: "Silverline Media",
    amount: 276500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-06-11" },
      { stage: "qualification", enteredDate: "2026-06-18" },
      { stage: "demo", enteredDate: "2026-06-25" },
      { stage: "proposal", enteredDate: "2026-07-02" }
    ],
    activities: [
      { type: "note", date: "2026-07-02" },
      { type: "email", date: "2026-06-26" }
    ],
  },
  {
    id: "opp-15",
    name: "Pilot to Paid Conversion",
    account: "Millbrook Manufacturing",
    amount: 12000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-05-05" },
      { stage: "qualification", enteredDate: "2026-05-12" },
      { stage: "demo", enteredDate: "2026-05-19" },
      { stage: "proposal", enteredDate: "2026-05-26" },
      { stage: "negotiation", enteredDate: "2026-06-02" }
    ],
    activities: [
      { type: "email", date: "2026-06-02" },
      { type: "meeting", date: "2026-05-27" },
      { type: "note", date: "2026-05-21" }
    ],
  },
  {
    id: "opp-16",
    name: "Renewal at Risk",
    account: "Redshank Analytics",
    amount: 55000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-07" },
      { stage: "qualification", enteredDate: "2026-07-14" },
      { stage: "demo", enteredDate: "2026-07-21" },
      { stage: "proposal", enteredDate: "2026-07-28" }
    ],
    activities: [
      { type: "email", date: "2026-07-28" },
      { type: "call", date: "2026-07-22" }
    ],
  },
  {
    id: "opp-17",
    name: "Core Platform Deal",
    account: "Cobalt Freight",
    amount: 285500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-04" },
      { stage: "qualification", enteredDate: "2026-07-11" },
      { stage: "demo", enteredDate: "2026-07-18" },
      { stage: "proposal", enteredDate: "2026-07-25" },
      { stage: "negotiation", enteredDate: "2026-08-01" }
    ],
    activities: [
      { type: "note", date: "2026-08-01" },
      { type: "meeting", date: "2026-07-26" }
    ],
  },
  {
    id: "opp-18",
    name: "Global Rollout Phase 2",
    account: "Harborstack Systems",
    amount: 40000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-06-30" },
      { stage: "qualification", enteredDate: "2026-07-07" },
      { stage: "demo", enteredDate: "2026-07-14" },
      { stage: "proposal", enteredDate: "2026-07-21" }
    ],
    activities: [
      { type: "note", date: "2026-07-21" },
      { type: "note", date: "2026-07-15" }
    ],
  },
  {
    id: "opp-19",
    name: "New Region Rollout",
    account: "Meridian Robotics",
    amount: 80000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-26" }
    ],
    activities: [
      { type: "meeting", date: "2026-08-21" },
      { type: "signature-received", date: "2026-08-26" }
    ],
  },
  {
    id: "opp-20",
    name: "Global Rollout Phase 2",
    account: "Beacon Health",
    amount: 100500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-20" },
      { stage: "qualification", enteredDate: "2026-08-27" }
    ],
    activities: [
      { type: "call", date: "2026-08-22" },
      { type: "contract-sent", date: "2026-08-27" }
    ],
  },
  {
    id: "opp-21",
    name: "Trial Extension Deal",
    account: "Foxglove Retail",
    amount: 258500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-14" },
      { stage: "qualification", enteredDate: "2026-08-21" },
      { stage: "demo", enteredDate: "2026-08-28" }
    ],
    activities: [
      { type: "email", date: "2026-08-23" },
      { type: "signature-received", date: "2026-08-28" }
    ],
  },
  {
    id: "opp-22",
    name: "Clinic Network Expansion",
    account: "Fernbank Media",
    amount: 232500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-25" }
    ],
    activities: [
      { type: "note", date: "2026-08-20" },
      { type: "contract-sent", date: "2026-08-25" }
    ],
  },
  {
    id: "opp-23",
    name: "Core Platform Deal",
    account: "Northwind Logistics",
    amount: 61500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-19" },
      { stage: "qualification", enteredDate: "2026-08-26" }
    ],
    activities: [
      { type: "meeting", date: "2026-08-22" },
      { type: "pricing-discussed", date: "2026-08-26" }
    ],
  },
  {
    id: "opp-24",
    name: "Platform Expansion",
    account: "Craft & Co",
    amount: 53500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-13" },
      { stage: "qualification", enteredDate: "2026-08-20" },
      { stage: "demo", enteredDate: "2026-08-27" }
    ],
    activities: [
      { type: "call", date: "2026-08-24" },
      { type: "pricing-discussed", date: "2026-08-27" }
    ],
  },
  {
    id: "opp-25",
    name: "Multi-Site Rollout",
    account: "Foxglove Retail",
    amount: 38500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-18" },
      { stage: "negotiation", enteredDate: "2026-08-25" }
    ],
    activities: [
      { type: "note", date: "2026-08-25" },
      { type: "call", date: "2026-08-19" }
    ],
  },
  {
    id: "opp-26",
    name: "Clinic Network Expansion",
    account: "Thistlewood Foods",
    amount: 153000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-14" },
      { stage: "closed-won", enteredDate: "2026-08-21" }
    ],
    activities: [
      { type: "contract-sent", date: "2026-08-17" },
      { type: "signature-received", date: "2026-08-21" }
    ],
  },
  {
    id: "opp-27",
    name: "Post-Merger Consolidation",
    account: "Quillfeather Media",
    amount: 272000,
    stageHistory: [
      { stage: "qualification", enteredDate: "2026-08-16" },
      { stage: "negotiation", enteredDate: "2026-08-23" }
    ],
    activities: [
      { type: "call", date: "2026-08-23" },
      { type: "email", date: "2026-08-17" },
      { type: "meeting", date: "2026-08-11" }
    ],
  },
  {
    id: "opp-28",
    name: "Add-On Module: Analytics",
    account: "Northwind Logistics",
    amount: 68000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-05" },
      { stage: "qualification", enteredDate: "2026-08-12" },
      { stage: "proposal", enteredDate: "2026-08-19" }
    ],
    activities: [
      { type: "call", date: "2026-08-19" },
      { type: "meeting", date: "2026-08-13" }
    ],
  },
  {
    id: "opp-29",
    name: "Trial Extension Deal",
    account: "Sparrowhawk Health",
    amount: 51500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-01" },
      { stage: "qualification", enteredDate: "2026-08-08" },
      { stage: "demo", enteredDate: "2026-08-15" },
      { stage: "closed-won", enteredDate: "2026-08-22" }
    ],
    activities: [
      { type: "contract-sent", date: "2026-08-18" },
      { type: "signature-received", date: "2026-08-22" }
    ],
  },
  {
    id: "opp-30",
    name: "Post-Merger Consolidation",
    account: "Quillfeather Media",
    amount: 279500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-10" },
      { stage: "demo", enteredDate: "2026-08-17" },
      { stage: "proposal", enteredDate: "2026-08-24" }
    ],
    activities: [
      { type: "call", date: "2026-08-24" },
      { type: "email", date: "2026-08-18" }
    ],
  },
  {
    id: "opp-31",
    name: "Multi-Site Rollout",
    account: "Ashgrove Higher Ed",
    amount: 258500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-22" },
      { stage: "qualification", enteredDate: "2026-07-29" },
      { stage: "demo", enteredDate: "2026-08-05" },
      { stage: "proposal", enteredDate: "2026-08-12" },
      { stage: "negotiation", enteredDate: "2026-08-19" },
      { stage: "closed-won", enteredDate: "2026-08-26" }
    ],
    activities: [
      { type: "call", date: "2026-08-26" },
      { type: "note", date: "2026-08-20" }
    ],
  },
  {
    id: "opp-32",
    name: "Post-Merger Consolidation",
    account: "Palisade Insurance",
    amount: 153500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-15" },
      { stage: "qualification", enteredDate: "2026-07-22" },
      { stage: "demo", enteredDate: "2026-07-29" },
      { stage: "proposal", enteredDate: "2026-08-05" },
      { stage: "negotiation", enteredDate: "2026-08-12" },
      { stage: "closed-won", enteredDate: "2026-08-19" }
    ],
    activities: [
      { type: "meeting", date: "2026-08-19" },
      { type: "note", date: "2026-08-13" },
      { type: "note", date: "2026-08-07" }
    ],
  },
  {
    id: "opp-33",
    name: "Flagship Store Program",
    account: "Brackenfield Energy",
    amount: 259000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-07" },
      { stage: "qualification", enteredDate: "2026-07-14" },
      { stage: "demo", enteredDate: "2026-07-21" },
      { stage: "proposal", enteredDate: "2026-07-28" },
      { stage: "negotiation", enteredDate: "2026-08-04" },
      { stage: "closed-won", enteredDate: "2026-08-11" }
    ],
    activities: [
      { type: "pricing-discussed", date: "2026-08-06" },
      { type: "call", date: "2026-08-11" }
    ],
  },
  {
    id: "opp-34",
    name: "Renewal at Risk",
    account: "Thistlewood Foods",
    amount: 171000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-19" },
      { stage: "qualification", enteredDate: "2026-07-26" },
      { stage: "demo", enteredDate: "2026-08-02" },
      { stage: "proposal", enteredDate: "2026-08-09" },
      { stage: "negotiation", enteredDate: "2026-08-16" },
      { stage: "closed-won", enteredDate: "2026-08-23" }
    ],
    activities: [
      { type: "meeting", date: "2026-08-23" },
      { type: "email", date: "2026-08-17" }
    ],
  },
  {
    id: "opp-35",
    name: "SMB Starter Package",
    account: "Fernbank Media",
    amount: 202500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-12" },
      { stage: "qualification", enteredDate: "2026-07-19" },
      { stage: "demo", enteredDate: "2026-07-26" },
      { stage: "proposal", enteredDate: "2026-08-02" },
      { stage: "negotiation", enteredDate: "2026-08-09" },
      { stage: "closed-won", enteredDate: "2026-08-16" }
    ],
    activities: [
      { type: "email", date: "2026-08-16" },
      { type: "call", date: "2026-08-10" },
      { type: "note", date: "2026-08-04" }
    ],
  },
  {
    id: "opp-36",
    name: "Compliance Add-On",
    account: "Brackenfield Energy",
    amount: 124500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-30" },
      { stage: "qualification", enteredDate: "2026-08-06" },
      { stage: "demo", enteredDate: "2026-08-13" },
      { stage: "proposal", enteredDate: "2026-08-20" },
      { stage: "negotiation", enteredDate: "2026-08-27" }
    ],
    activities: [

    ],
  },
  {
    id: "opp-37",
    name: "Flagship Store Program",
    account: "Sparrowhawk Health",
    amount: 290000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-07" },
      { stage: "qualification", enteredDate: "2026-08-14" },
      { stage: "demo", enteredDate: "2026-08-21" },
      { stage: "proposal", enteredDate: "2026-08-28" }
    ],
    activities: [

    ],
  },
  {
    id: "opp-38",
    name: "Clinic Network Expansion",
    account: "Brackenfield Energy",
    amount: 243000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-25" },
      { stage: "qualification", enteredDate: "2026-08-01" },
      { stage: "demo", enteredDate: "2026-08-08" },
      { stage: "proposal", enteredDate: "2026-08-15" },
      { stage: "negotiation", enteredDate: "2026-08-22" }
    ],
    activities: [

    ],
  },
  {
    id: "opp-39",
    name: "Global Rollout Phase 2",
    account: "Harborstack Systems",
    amount: 237000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-05" },
      { stage: "qualification", enteredDate: "2026-08-12" },
      { stage: "demo", enteredDate: "2026-08-19" },
      { stage: "proposal", enteredDate: "2026-08-26" }
    ],
    activities: [
      { type: "call", date: "2026-08-26" }
    ],
  },
  {
    id: "opp-40",
    name: "Post-Merger Consolidation",
    account: "Northwind Logistics",
    amount: 41500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-28" },
      { stage: "qualification", enteredDate: "2026-08-04" },
      { stage: "demo", enteredDate: "2026-08-11" },
      { stage: "proposal", enteredDate: "2026-08-18" },
      { stage: "negotiation", enteredDate: "2026-08-25" }
    ],
    activities: [
      { type: "email", date: "2026-08-25" }
    ],
  },
  {
    id: "opp-41",
    name: "Global Rollout Phase 2",
    account: "Solstice Retail",
    amount: 109000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-08" },
      { stage: "qualification", enteredDate: "2026-08-15" },
      { stage: "demo", enteredDate: "2026-08-22" },
      { stage: "proposal", enteredDate: "2026-08-29" }
    ],
    activities: [
      { type: "meeting", date: "2026-08-29" }
    ],
  },
  {
    id: "opp-42",
    name: "Campus Rollout",
    account: "Millbrook Manufacturing",
    amount: 220500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-06-24" },
      { stage: "qualification", enteredDate: "2026-07-01" },
      { stage: "demo", enteredDate: "2026-07-08" },
      { stage: "proposal", enteredDate: "2026-07-15" },
      { stage: "negotiation", enteredDate: "2026-07-22" }
    ],
    activities: [
      { type: "call", date: "2026-07-22" }
    ],
  },
  {
    id: "opp-43",
    name: "Warehouse Automation Suite",
    account: "Beacon Health",
    amount: 38500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-06-16" },
      { stage: "qualification", enteredDate: "2026-06-23" },
      { stage: "demo", enteredDate: "2026-06-30" },
      { stage: "proposal", enteredDate: "2026-07-07" }
    ],
    activities: [
      { type: "email", date: "2026-07-07" }
    ],
  },
  {
    id: "opp-44",
    name: "Global Rollout Phase 2",
    account: "Copperfield Logistics",
    amount: 260500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-05" },
      { stage: "negotiation", enteredDate: "2026-07-12" }
    ],
    activities: [
      { type: "call", date: "2026-07-12" },
      { type: "meeting", date: "2026-07-06" }
    ],
  },
  {
    id: "opp-45",
    name: "Platform Expansion",
    account: "Wickerdown Supply",
    amount: 23500,
    stageHistory: [
      { stage: "qualification", enteredDate: "2026-07-09" },
      { stage: "proposal", enteredDate: "2026-07-16" }
    ],
    activities: [
      { type: "email", date: "2026-07-16" },
      { type: "call", date: "2026-07-10" }
    ],
  },
  {
    id: "opp-46",
    name: "Platform Expansion",
    account: "Ledgerline Finance",
    amount: 114500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-18" },
      { stage: "closed-won", enteredDate: "2026-08-25" }
    ],
    activities: [
      { type: "email", date: "2026-08-25" },
      { type: "email", date: "2026-08-19" }
    ],
  },
  {
    id: "opp-47",
    name: "Annual Renewal + Seats",
    account: "Redshank Analytics",
    amount: 104000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-08" },
      { stage: "qualification", enteredDate: "2026-08-15" },
      { stage: "closed-won", enteredDate: "2026-08-22" }
    ],
    activities: [
      { type: "email", date: "2026-08-22" },
      { type: "note", date: "2026-08-16" },
      { type: "email", date: "2026-08-10" }
    ],
  },
  {
    id: "opp-48",
    name: "Alumni Portal Upgrade",
    account: "Amberwell Insurance",
    amount: 213500,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-08-19" },
      { stage: "demo", enteredDate: "2026-08-26" }
    ],
    activities: [
      { type: "note", date: "2026-08-21" },
      { type: "contract-sent", date: "2026-08-26" }
    ],
  },
  {
    id: "opp-49",
    name: "New Region Rollout",
    account: "Harborstack Systems",
    amount: 82500,
    stageHistory: [
      { stage: "qualification", enteredDate: "2026-08-20" },
      { stage: "demo", enteredDate: "2026-08-27" }
    ],
    activities: [
      { type: "meeting", date: "2026-08-22" },
      { type: "pricing-discussed", date: "2026-08-27" }
    ],
  },
  {
    id: "opp-50",
    name: "District-Wide License",
    account: "Palisade Insurance",
    amount: 269000,
    stageHistory: [
      { stage: "discovery", enteredDate: "2026-07-24" },
      { stage: "qualification", enteredDate: "2026-07-31" },
      { stage: "demo", enteredDate: "2026-08-07" },
      { stage: "proposal", enteredDate: "2026-08-14" },
      { stage: "negotiation", enteredDate: "2026-08-21" },
      { stage: "closed-won", enteredDate: "2026-08-28" }
    ],
    activities: [
      { type: "call", date: "2026-08-28" }
    ],
  },
];

